FROM python:3.9-slim

WORKDIR /app

# Install system dependencies for OpenCV and TensorFlow
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libstdc++6 \
    && apt-get clean

COPY ./src/python/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY ./src/python ./ 

# Expose the Flask port
EXPOSE 5000

CMD ["python", "main.py"]