# Set the base image
FROM node:20

# Set working directory
WORKDIR /var/www/cfoam/vue

# Copy `package.json` and `package-lock.json`
COPY ./src/vue/package*.json ./

# Install project dependencies
RUN npm install --legacy-peer-deps

# Copy project files into the docker image
# COPY ./src/vue ./

# Expose the port Vite runs on
# EXPOSE 3000

# Start the Vite server
# CMD ["npm", "run", "dev"]